name: roam_the_world_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9
  firebase_core:
  firebase_auth:
  firebase_messaging:
  cloud_firestore:
  flutter_stripe:
  url_launcher:
  restart_app:
  app_settings:
  flutter_easyloading:
  flutter_local_notifications:
  flutter_map:
  geolocator: ^9.0.2  # Try this version
  geocoding: ^2.1.0
  google_places_flutter: ^2.1.0
  flutter_typeahead:
  latlong2:
  flutter_google_maps_webservices: ^1.1.1
  flutter_google_places_sdk: ^0.3.0
  googleapis_auth:
  firebase_in_app_messaging:
  image_picker:
  intl:
#  geolocator:
  firebase_storage:
  http:
  flutter_easy_faq: ^1.0.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.8.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  google_maps_flutter:
  multi_select_flutter: ^4.1.3
  pin_code_fields: ^8.0.1
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/


