// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4JBHi_RJ_sKNpw8y0bFABpuIADLQr-4w',
    appId: '1:676158442179:web:bfcaddbd64ce08cbb2b076',
    messagingSenderId: '676158442179',
    projectId: 'roamtheworld-325c4',
    authDomain: 'roamtheworld-325c4.firebaseapp.com',
    storageBucket: 'roamtheworld-325c4.firebasestorage.app',
    measurementId: 'G-8N4QEMVZ4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5yoeaMOFrLjWU8aiGkVkNuMwYVrzqIvI',
    appId: '1:676158442179:android:5a8b794a54a47517b2b076',
    messagingSenderId: '676158442179',
    projectId: 'roamtheworld-325c4',
    storageBucket: 'roamtheworld-325c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgetfVTq-voR8ahuPW2iKfGBpFCvhwYGM',
    appId: '1:676158442179:ios:2b608f4c9f98e449b2b076',
    messagingSenderId: '676158442179',
    projectId: 'roamtheworld-325c4',
    storageBucket: 'roamtheworld-325c4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgetfVTq-voR8ahuPW2iKfGBpFCvhwYGM',
    appId: '1:676158442179:ios:2b608f4c9f98e449b2b076',
    messagingSenderId: '676158442179',
    projectId: 'roamtheworld-325c4',
    storageBucket: 'roamtheworld-325c4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4JBHi_RJ_sKNpw8y0bFABpuIADLQr-4w',
    appId: '1:676158442179:web:60f06542d377b36ab2b076',
    messagingSenderId: '676158442179',
    projectId: 'roamtheworld-325c4',
    authDomain: 'roamtheworld-325c4.firebaseapp.com',
    storageBucket: 'roamtheworld-325c4.firebasestorage.app',
    measurementId: 'G-0ZL75DP4X5',
  );
}
